AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Connect custom resources like Queues and Hours of Operation.

Parameters:
  ConnectInstanceArn:
    Type: String
    Description: The ARN of the AWS Connect instance.
    AllowedPattern: '^arn:aws[a-zA-Z-]*:connect:[a-z0-9-]*:[0-9]{12}:instance\/[a-zA-Z0-9-]{36}$'
    ConstraintDescription: Must be a valid AWS Connect instance ARN.

Resources:
  MainHoursOfOperation:
    Type: 'AWS::Connect::HoursOfOperation'
    Properties:
      Name: 'MainOfficeHours'
      Description: 'Main office hours (9 AM to 5 PM EST, Mon-Fri)'
      InstanceArn: !Ref ConnectInstanceArn
      TimeZone: 'America/New_York'
      Config:
        - Day: 'MONDAY'
          StartTime:
            Hours: 9
            Minutes: 0
          EndTime:
            Hours: 17
            Minutes: 0
        - Day: 'TUESDAY'
          StartTime:
            Hours: 9
            Minutes: 0
          EndTime:
            Hours: 17
            Minutes: 0
        - Day: 'WEDNESDAY'
          StartTime:
            Hours: 9
            Minutes: 0
          EndTime:
            Hours: 17
            Minutes: 0
        - Day: 'THURSDAY'
          StartTime:
            Hours: 9
            Minutes: 0
          EndTime:
            Hours: 17
            Minutes: 0
        - Day: 'FRIDAY'
          StartTime:
            Hours: 9
            Minutes: 0
          EndTime:
            Hours: 17
            Minutes: 0
      Tags:
        - Key: 'iac'
          Value: 'cloudformation'

  MainQueue:
    Type: 'AWS::Connect::Queue'
    Properties:
      Name: 'MainQueue'
      Description: 'Main queue for incoming calls.'
      HoursOfOperationArn: !GetAtt MainHoursOfOperation.Arn
      InstanceArn: !Ref ConnectInstanceArn
      Status: 'ENABLED'
      Tags:
        - Key: 'iac'
          Value: 'cloudformation' 